# https://github.com/fmzu/hascii/blob/main/.github/workflows/deploy.yml

name: ãƒ‡ãƒ—ãƒ­ã‚¤

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    name: ãƒã‚§ãƒƒã‚¯
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸ‘©â€ğŸ’» ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
        uses: actions/checkout@v4
      - name: ğŸ”¨ Bunã‚’æœ‰åŠ¹ã«ã™ã‚‹
        uses: oven-sh/setup-bun@v1
      - name: ğŸ”¨ ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
        run: bun install
      - name: ğŸ§ª ãƒ†ã‚¹ãƒˆ
        run: bun test
  deploy:
    name: ãƒ‡ãƒ—ãƒ­ã‚¤
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸ‘©â€ğŸ’» ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
        uses: actions/checkout@v4
      - name: ğŸ”¨ Bunã‚’æœ‰åŠ¹ã«ã™ã‚‹
        uses: oven-sh/setup-bun@v1
      - name: ğŸ”¨ ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
        run: bun install
      - name: ğŸ’ª ãƒ“ãƒ«ãƒ‰
        run: bun --cwd ui remix vite:build
      - name: ğŸš€ ãƒ‡ãƒ—ãƒ­ã‚¤ API
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy index.ts --name=timetable-api
          workingDirectory: api
      - name: ğŸš€ ãƒ‡ãƒ—ãƒ­ã‚¤ ã‚¦ã‚§ãƒ–ã‚µã‚¤ãƒˆ
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./build/client --project-name=timetable
          workingDirectory: ui
